# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField(default=0)),
                ('var2', models.IntegerField(default=0)),
                ('var3', models.IntegerField(default=0)),
                ('var4', models.IntegerField(default=0)),
            ],
        ),
    ]
