# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160509_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('emailid', models.EmailField(max_length=254)),
                ('session_id', models.CharField(blank=True, max_length=10000)),
                ('is_loggedin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
    ]
