# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rest1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, default='0000', max_length=20),
            preserve_default=False,
        ),
    ]
