# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160510_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rest1',
            new_name='interest1',
        ),
    ]
