# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160510_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nterest2',
            new_name='interest2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nterest3',
            new_name='interest3',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nterest4',
            new_name='interest4',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nterest5',
            new_name='interest5',
        ),
    ]
