# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160510_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest2',
            field=models.BooleanField(default='er'),
        ),
    ]
