# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160510_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest1',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest2',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest3',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest4',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest5',
            field=models.NullBooleanField(default=False),
        ),
    ]
