# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20160510_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
