# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
