# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_userprofile_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilepic',
            new_name='picture',
        ),
    ]
