# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(default='nocollege', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailid',
            field=models.EmailField(default='noeid', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='nopass', max_length=20),
            preserve_default=False,
        ),
    ]
