# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160510_0252'),
        ('polls', '0007_auto_20160509_0245'),
    ]

    operations = [
    ]
