# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
