# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20160730_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=8)),
                ('questionText', models.CharField(max_length=5000)),
                ('option1Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option2Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option3Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option4Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option5Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option6Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option7Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option8Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option9Text', models.CharField(blank=True, max_length=500, null=True)),
                ('option10Text', models.CharField(blank=True, max_length=500, null=True)),
                ('answerSeq', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuizGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=1000)),
                ('quizname', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='QuizReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=1000)),
                ('passwd', models.CharField(max_length=1000)),
            ],
        ),
    ]
