# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20160731_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='permaadd',
        ),
    ]
