# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20160812_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizglobal',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
