# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20160815_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizglobal',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='marking',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='mmcc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='mmci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='mscc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='msci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='prizes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
